// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

type SchemaMigration struct {
	Version string `json:"version"`
}

type Todos2 struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}
